#!/usr/bin/env bash
#
# Build the standalone BCM43455 WiFi bring-up probe for aarch64-phoenix.
#
# Produces a single static ELF (wifi-probe) that reproduces the
# 2026-06-04 firmware-download + ARM-CR4-release baseline. Links directly
# with the toolchain's default libphoenix + CRT (same as the ported
# rpi4-hwrng / rpi4-vcmbox userspace drivers) — no phoenix-rtos-build
# tree, no image rebuild. Nothing in the default published image
# references this binary, so the normal build is unaffected; it exists
# only if you run this script.
#
# Copyright 2026 Phoenix Systems
# SPDX-License-Identifier: BSD-3-Clause
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

# Toolchain gcc (override with GCC=... if your toolchain lives elsewhere).
GCC="${GCC:-$REPO_ROOT/.toolchain/aarch64-phoenix/bin/aarch64-phoenix-gcc}"
NM="${NM:-$REPO_ROOT/.toolchain/aarch64-phoenix/bin/aarch64-phoenix-nm}"

# The firmware / NVRAM C-arrays are UNTRACKED generated artifacts that
# live in the lwip-port dir (produced by scripts/gen-wifi-fw-c.sh from the
# .firmware/ blobs). Override LWIP_PORT if they live elsewhere.
LWIP_PORT="${LWIP_PORT:-$REPO_ROOT/sources/phoenix-rtos-lwip/port}"

FW_C="$LWIP_PORT/wifi-fw-43455.c"
NVRAM_C="$LWIP_PORT/wifi-nvram-43455.c"

OUT="${OUT:-$HERE/wifi-probe}"

for f in "$GCC" "$FW_C" "$NVRAM_C" \
	"$LWIP_PORT/wifi-fw-43455.h" "$LWIP_PORT/wifi-nvram-43455.h"; do
	if [ ! -e "$f" ]; then
		echo "wifi-probe/build.sh: missing required input: $f" >&2
		echo "  (firmware arrays are generated by scripts/gen-wifi-fw-c.sh)" >&2
		exit 1
	fi
done

CFLAGS_PROBE="-O2 -Wall -Wextra -std=gnu11 -I$LWIP_PORT"
# The 3.9 MB firmware array is pure data — compile it at -O0 (high opt is
# slow + memory-heavy for zero codegen benefit).
CFLAGS_DATA="-O0 -I$LWIP_PORT"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "wifi-probe: compiling probe logic (-O2)"
"$GCC" $CFLAGS_PROBE -c "$HERE/wifi-probe.c" -o "$TMP/wifi-probe.o"

echo "wifi-probe: compiling firmware array (-O0, ~3.9 MB)"
"$GCC" $CFLAGS_DATA -c "$FW_C" -o "$TMP/wifi-fw-43455.o"

echo "wifi-probe: compiling nvram array (-O0)"
"$GCC" $CFLAGS_DATA -c "$NVRAM_C" -o "$TMP/wifi-nvram-43455.o"

echo "wifi-probe: linking $OUT"
"$GCC" -O2 \
	"$TMP/wifi-probe.o" \
	"$TMP/wifi-fw-43455.o" \
	"$TMP/wifi-nvram-43455.o" \
	-o "$OUT"

echo "wifi-probe: undefined-symbol check (expect none):"
if "$NM" -u "$OUT" | grep -q .; then
	echo "  !! UNDEFINED SYMBOLS PRESENT:" >&2
	"$NM" -u "$OUT" >&2
	exit 1
fi
echo "  0 undefined symbols."

echo "wifi-probe: done -> $OUT"
file "$OUT" || true
ls -la "$OUT"
