#!/usr/bin/env bash
# Regenerate cr4tiny_blob.h from cr4tiny.s (the #91 trivial-program test blob).
# Requires llvm-mc + llvm-objcopy (Thumb-2 target). The blob is an 8 KiB image
# whose reset vector [0..3] is the REAL brcmfmac43455 fw's verbatim Thumb-2 B.W
# into rambase+0x80, where a tiny counter loop lives; the counter target
# 0x199000 (blob offset 0x1000) stays zero for a known pre-state.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
llvm-mc -triple=thumbv7-none-eabi -filetype=obj "$here/cr4tiny.s" -o "$tmp/cr4tiny.o"
llvm-objcopy -O binary --only-section=.text "$tmp/cr4tiny.o" "$tmp/cr4tiny.bin"
python3 - "$tmp/cr4tiny.bin" "$here/cr4tiny_blob.h" <<'PY'
import sys
code = open(sys.argv[1],"rb").read()
BLOB = 8192
b = bytearray(BLOB)
b[0:4] = bytes([0x98,0xf1,0x3e,0xb8])   # Thumb-2 B.W addr0 -> rambase+0x80
b[0x80:0x80+len(code)] = code
with open(sys.argv[2],"w") as f:
    f.write("/* AUTO-GENERATED by gen-cr4tiny.sh (cr4tiny.s via llvm-mc). Do not edit by hand.\n")
    f.write(" * Trivial CR4 program for the #91 firmware-execution gate 'trivial-program test':\n")
    f.write(" *   [0..3]   = 0xb83ef198  Thumb-2 B.W from reset (addr 0) to rambase+0x80 (verbatim real-fw vector)\n")
    f.write(" *   [0x80..] = counter loop: *(0x199000) = 0xC0DE0001, then increment forever (Thumb-2)\n")
    f.write(" *   counter target 0x199000 (blob offset 0x1000) is zero here => known pre-state.\n")
    f.write(" * Increment observed at 0x199000 after release => the CR4 executes our code (release path works).\n")
    f.write(" * Dead (still 0) => the release path itself is broken (wrong core / reset semantics). */\n")
    f.write("#ifndef CR4TINY_BLOB_H\n#define CR4TINY_BLOB_H\n#include <stdint.h>\n\n")
    f.write("#define CR4TINY_COUNTER_ADDR 0x00199000u\n")
    f.write("#define CR4TINY_COUNTER_MAGIC 0xC0DE0001u\n\n")
    f.write("static const uint32_t cr4tiny_blob_len = %du;\n" % BLOB)
    f.write("static const uint8_t cr4tiny_blob[%d] = {\n" % BLOB)
    for i in range(0, BLOB, 16):
        f.write("\t" + ", ".join("0x%02x" % x for x in b[i:i+16]) + ",\n")
    f.write("};\n\n#endif /* CR4TINY_BLOB_H */\n")
print("regenerated", sys.argv[2])
PY
